services:
  subme:
    image: ghcr.io/shiyanyx/subme:latest
    container_name: subme
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./collectors:/app/collectors
      - ./cache:/app/cache
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
