version: "3.8"

services:
  subme:
    build: .
    container_name: subme
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./collectors:/app/collectors
      - ./cache:/app/cache
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
